name: CI

on: [push, pull_request]

jobs:
  ubuntu:
    strategy:
      fail-fast: false

      matrix:
        ruby: ['3.2', '3.1', '3.0', '2.7', 'jruby']
        rails: ['7.0', '6.1']
        include:
          - ruby: '3.0'
            rails: '6.0'

          - ruby: '2.7'
            rails: '6.0'

          - ruby: '2.6'
            rails: '6.1'
          - ruby: '2.6'
            rails: '6.0'
          - ruby: '2.6'
            rails: '5.2'

          - ruby: '2.5'
            rails: '6.1'
          - ruby: '2.5'
            rails: '5.2'

          - ruby: '2.4'
            rails: '5.2'
          - ruby: '2.4'
            rails: '5.1'
          - ruby: '2.4'
            rails: '4.2'

          - ruby: '2.3'
            rails: '5.2'
          - ruby: '2.3'
            rails: '4.2'

          - ruby: '2.2'
            rails: '5.2'
          - ruby: '2.2'
            rails: '5.0'
          - ruby: '2.2'
            rails: '4.2'

          - ruby: '2.1'
            rails: '4.2'

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          rubygems: ${{ (matrix.ruby_version < '2.6' && 'default') || 'latest' }}
          bundler-cache: true
        continue-on-error: ${{ matrix.ruby == 'jruby' }}

      - run: bundle e rake
        continue-on-error: ${{ matrix.ruby == 'jruby' }}
